In [5]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [6]:
cd/content/gdrive/My Drive/pandas

/content/gdrive/My Drive/pandas

In [7]:
import pandas as pd

In [9]:
df=pd.read_csv('./data/friend_list.csv')
df

    name  age        job
0   John   20    student
1  Jenny   30  developer
2   Nate   30    teacher
3  Julia   40    dentist
4  Brian   45    manager
5  Chris   25     intern

In [10]:
#select row
df[1:3]

    name  age        job
1  Jenny   30  developer
2   Nate   30    teacher

In [11]:
df.loc[[0,3]]

    name  age      job
0   John   20  student
3  Julia   40  dentist

In [13]:
df_filtered=df[df.age>30]
df_filtered

    name  age      job
3  Julia   40  dentist
4  Brian   45  manager

In [17]:
df_filtered=df[(df.age>30) & (df.name=='Julia')]
df_filtered

    name  age      job
3  Julia   40  dentist

In [24]:
df.iloc[:,0:2]

    name  age
0   John   20
1  Jenny   30
2   Nate   30
3  Julia   40
4  Brian   45
5  Chris   25

In [25]:
df_filtered = df[['name', 'age']]
df_filtered

    name  age
0   John   20
1  Jenny   30
2   Nate   30
3  Julia   40
4  Brian   45
5  Chris   25